on: [push]
name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        subscriptionId: c00d16c7-6c1f-4c03-9be1-6934a4c49682
        resourceGroupName: vnm-aks-pf-reuse-rg
        template: html/webapp/ArmTemplates/windows-webapp-template.json
        parameters: webAppName=vnm-arm-action hostingPlanName=dikhakha121 appInsightsLocation="Central US"
        deploymentName: github-advanced-test
    - run: echo ${{ steps.deploy.outputs.hostName }}

